# Trade Values
RESOLUTION = "5MINS"
ZSCORE_THRESH = 1.5
MAX_HALF_LIFE = 23
WINDOW = 24
USD_PER_TRADE = 30
USD_MIN_COLLATERAL = 30
TP_AMOUNT = 0.05

# Find Cointegrated Pairs
FIND_COINTEGRATED_PAIRS = True

# Place Trades
PLACE_TRADES = True

# DYDX ACCOUNT
DYDX_ADDRESS = ''
DYDX_MNEMONIC = ''

# Telegram info
TELEGRAM_TOKEN = "7049563480:AAFVYyIi05JzUkeIvvGFvhsU0Dv_1dBNujI"
TELEGRAM_CHAT_ID = "6812839461"

